##
## EPITECH PROJECT, 2021
## B-OOP-400-BDX-4-1-arcade-mathis.fayet
## File description:
## Makefile
##

RM_F	=	rm -f

CC		= 	g++

NAME	=	# le .so

SRC		=	src/Pacman.cpp

SRC_OBJ	=	$(SRC:.cpp=.o)

all: $(NAME)

clean:
	# RM_F les (OBJS)
fclean:
	# RM_F le .so

re: fclean all